utils: prompts: add prompt_for_app_ident
Trying to deploy an app with a dot(.) or spaces( ) cause GraphQL API
failures, as in,
  error: could not create app in the backend
  │   1: could not publish app
  ╰─▶ 2: GraphQL API failure: App name `tmp .cWmMN5keRo` provided is invalid

And,
  error: could not create app in the backend
  │   1: could not publish app
  ╰─▶ 2: GraphQL API failure: App name `tmp dadRZuK0CqK4` provided is invalid

Fixes #5341

Signed-off-by: Charalampos Mitrodimas <charmitro@posteo.net>