examples: engine: fix doc comment target name
Issue was,
  $ cargo run --example engine-universal --release --features "cranelift"
  error: no example target named `engine-universal`.

On Cargo.toml we specify this target with,
  [[example]]
  name = "engine"
  path = "examples/engine.rs"
  required-features = ["cranelift"]

Signed-off-by: Charalampos Mitrodimas <charmitro@posteo.net>