Progress reporting for module loading and compilation (#5883)
* feat: Progress reporting and abort for module compilation

Add a new Module::new_with_progress function, which will call a progress
callback with progress information.

The callback may also return an error , which will abort compilation.

* feat(wasix): Module load/compile progress reporting

Implement progress reporting for module loading.

* Extends ModuleCache with a load_with_progress() method, which receives
  a progress callback

* Clean up and unify the module loading methods on the Runtime trait.
  Replace old methods with a new, general fn resolve_module(), which
  replaces all the old methods.
  This new method also takes an optional progress callback.

* feat(cli): run command: Show compilation progress

Show compilation progress using the newly added progress tracking.

* Fix clippy warnings

* Rename CompileError::User to CompileError::Aborted

Makes more sense.

* Refactor Module::new_with_progress to ProgressEngineExt::new_module_with_progress

To keep the main API clean.

* tests: Add module compile progress/abort tests

* chore(cli): Improve module compilation progress status

* Lift ProgressContext to wasmer-compiler crate

To enable reuse.

* Extend singlepass compiler with progress reporting.

* Include trampolines in compilation progress.

* Add singlepass progress tests

* chore: Docs improvements and small clippy fixes

* tmp

* fix cranelift testse

* remove dbg output

* use correct runtime

* refactor

* remove from_binary_with_progress from BackendModule trait

* simplify

* drop progress_ext

* use thiserror for UserAbort

* move tests to tests/compilers

* fix singlepass progress bar

* run progress tests for all compilers

* fix compilation error based on configuration

* fix conditional build

* fix cargo fmt

* remove unused imports

---------

Co-authored-by: Martin Liska <martin.liska@hey.com>